# folder_path=$(pwd)
# # 循环判断.bag文件体积是否超过50GB且数量大于6
# while true; do
#     total_size=$(du -c $folder_path/*.bag 2>/dev/null | grep total | awk '{print $1}')

#     file_count=$(ls -l $folder_path/*.bag 2>/dev/null | wc -l)

#     if [ -z "$total_size" ]; then
#         total_size=0
#     fi

#     if [ $total_size -le 52428800 ] && [ $file_count -le 6 ]; then
#         echo "文件夹中.bag文件体积小于等于5GB且文件数量不超过3个，停止删除操作"
#         break
#     fi

#     if [ $total_size -gt 52428800 ] && [ $file_count -gt 6 ]; then
#         oldest_file=$(ls -t $folder_path/*.bag | tail -1)
#         rm $oldest_file
#         echo "删除文件：$oldest_file"
#     else
#         largest_file=$(ls -S $folder_path/*.bag | head -1)
#         rm $largest_file
#         echo "删除文件：$largest_file"
#     fi
# done

rosbag record --tcpnodelay \
/drone0/mapping_vis/vs_gridmap_inflate \
/car_state \
/clicked_point \
/diagnostics \
/drone0/depth \
/drone0/gridmap \
/drone0/imu \
/drone0/mapping/local_pointcloud \
/drone0/mapping/mask_cloud \
/drone0/odom \
/drone0/odom_visualization/cmd \
/drone0/odom_visualization/covariance \
/drone0/odom_visualization/covariance_velocity \
/drone0/odom_visualization/fov_visual \
/drone0/odom_visualization/height \
/drone0/odom_visualization/path \
/drone0/odom_visualization/pose \
/drone0/odom_visualization/robot \
/drone0/odom_visualization/robot_array \
/drone0/odom_visualization/sensor \
/drone0/odom_visualization/trajectory \
/drone0/odom_visualization/velocity \
/drone0/planning/car_predict \
/drone0/planning/check_pts \
/drone0/planning/debug_pts \
/drone0/planning/drone_vel \
/drone0/planning/drone_vel_array \
/drone0/planning/invalid_pts \
/drone0/planning/observable_margin \
/drone0/planning/polyhedra \
/drone0/planning/ray \
/drone0/planning/ray_array \
/drone0/planning/target_vel \
/drone0/planning/target_vel_array \
/drone0/planning/traj \
/drone0/planning/visible_ps \
/drone0/position_cmd \
/drone0/replanState \
/drone0/setpoints_cmd \
/drone0/so3cmd \
/drone0/trajectory \
/ekf/acc_filtered \
/ekf/cam_ekf_odom \
/ekf/gt_ \
/ekf_fuser/odom \
/global_map \
/initialpose \
/land_triger \
/laserMapping/odometry \
/laserMapping/path \
/livox/imu \
/object_odom_dtc2brig \
/tag_detections \
/tag_detections_image \
/tag_detections_position \
/target/odom \
/target_ekf_odom \
/target_original_odom \
/tf \
/tf_static \
/traj_start_trigger \
/triger \
/map_generator/click_map \
/map_generator/global_cloud \
/mavlink/from \
/mavlink/gcs_ip \
/mavlink/to \
/mavros/actuator_control \
/mavros/adsb/send \
/mavros/adsb/vehicle \
/mavros/altitude \
/mavros/battery \
/mavros/cam_imu_sync/cam_imu_stamp \
/mavros/camera/image_captured \
/mavros/cellular_status/status \
/mavros/companion_process/status \
/mavros/debug_value/debug \
/mavros/debug_value/debug_float_array \
/mavros/debug_value/debug_vector \
/mavros/debug_value/named_value_float \
/mavros/debug_value/named_value_int \
/mavros/debug_value/send \
/mavros/esc_info \
/mavros/esc_status \
/mavros/esc_telemetry \
/mavros/estimator_status \
/mavros/extended_state \
/mavros/fake_gps/mocap/tf \
/mavros/geofence/waypoints \
/mavros/global_position/compass_hdg \
/mavros/global_position/global \
/mavros/global_position/gp_lp_offset \
/mavros/global_position/gp_origin \
/mavros/global_position/local \
/mavros/global_position/raw/fix \
/mavros/global_position/raw/gps_vel \
/mavros/global_position/raw/satellites \
/mavros/global_position/rel_alt \
/mavros/global_position/set_gp_origin \
/mavros/gps_input/gps_input \
/mavros/gps_rtk/rtk_baseline \
/mavros/gps_rtk/send_rtcm \
/mavros/gpsstatus/gps1/raw \
/mavros/gpsstatus/gps1/rtk \
/mavros/gpsstatus/gps2/raw \
/mavros/gpsstatus/gps2/rtk \
/mavros/hil/actuator_controls \
/mavros/hil/controls \
/mavros/hil/gps \
/mavros/hil/imu_ned \
/mavros/hil/optical_flow \
/mavros/hil/rc_inputs \
/mavros/hil/state \
/mavros/home_position/home \
/mavros/home_position/set \
/mavros/imu/data \
/mavros/imu/data_raw \
/mavros/imu/diff_pressure \
/mavros/imu/mag \
/mavros/imu/static_pressure \
/mavros/imu/temperature_baro \
/mavros/imu/temperature_imu \
/mavros/landing_target/lt_marker \
/mavros/landing_target/pose \
/mavros/landing_target/pose_in \
/mavros/local_position/accel \
/mavros/local_position/odom \
/mavros/local_position/pose \
/mavros/local_position/pose_cov \
/mavros/local_position/velocity_body \
/mavros/local_position/velocity_body_cov \
/mavros/local_position/velocity_local \
/mavros/log_transfer/raw/log_data \
/mavros/log_transfer/raw/log_entry \
/mavros/mag_calibration/report \
/mavros/mag_calibration/status \
/mavros/manual_control/control \
/mavros/manual_control/send \
/mavros/mission/reached \
/mavros/mission/waypoints \
/mavros/mocap/pose \
/mavros/mount_control/command \
/mavros/mount_control/orientation \
/mavros/mount_control/status \
/mavros/nav_controller_output \
/mavros/obstacle/send \
/mavros/odometry/in \
/mavros/odometry/out \
/mavros/onboard_computer/status \
/mavros/param/param_value \
/mavros/play_tune \
/mavros/L_Ctrlflow/ground_distance \
/mavros/L_Ctrlflow/raw/optical_flow_rad \
/mavros/L_Ctrlflow/raw/send \
/mavros/L_Ctrlflow/temperature \
/mavros/radio_status \
/mavros/rallypoint/waypoints \
/mavros/rc/in \
/mavros/rc/out \
/mavros/rc/override \
/mavros/setpoint_accel/accel \
/mavros/setpoint_attitude/cmd_vel \
/mavros/setpoint_attitude/thrust \
/mavros/setpoint_position/global \
/mavros/setpoint_position/global_to_local \
/mavros/setpoint_position/local \
/mavros/setpoint_raw/attitude \
/mavros/setpoint_raw/global \
/mavros/setpoint_raw/local \
/mavros/setpoint_raw/target_attitude \
/mavros/setpoint_raw/target_global \
/mavros/setpoint_raw/target_local \
/mavros/setpoint_trajectory/desired \
/mavros/setpoint_trajectory/local \
/mavros/setpoint_velocity/cmd_vel \
/mavros/setpoint_velocity/cmd_vel_unstamped \
/mavros/state \
/mavros/statustext/recv \
/mavros/statustext/send \
/mavros/sys_status \
/mavros/target_actuator_control \
/mavros/terrain/report \
/mavros/time_reference \
/mavros/timesync_status \
/mavros/trajectory/desired \
/mavros/trajectory/generated \
/mavros/trajectory/path \
/mavros/tunnel/in \
/mavros/tunnel/out \
/mavros/vfr_hud \
/mavros/vision_pose/pose \
/mavros/vision_pose/pose_cov \
/mavros/vision_speed/speed_twist_cov \
/mavros/wind_estimation \
