#使用说明   1.该动能包提供4种多点控制的模式：1.只进行多点规划  2.进行多点规划并且实现yaw角控制  3.进行多点规划并且实现每个点的停留时间控制  4.进行多点规划并且实现每个点的停留时间控制以及yaw角控制
#          2.四种模式中的每个数组元素个数分别要满足3、4、4、5，否则读取失败，以下是满足要求的测试案例。
#          3.启动节点后，在rivz中发送一次2D Nav Goal即可进行规划。


#模式1    x y z 
test1:
  - [-18, 0.0, 1.2]  # Point 1 
  - [0,   8.0, 1.2]    # Point 2   
  - [0,  -2.0, 1.2]   # Point 3

# 模式2   x y z yaw  
test2:
  - [-18, 0.0, 1.2, 3.14]  # Point 1 
  - [0,   8.0, 1.2, -100]  # Point 2   
  - [0,  -2.0, 1.2, -100] # Point 3

# 模式3   x y z time
test3:
  - [-18, 0.0, 1.0, 3]  # Point 1 
  - [0,   8.0, 1.2, 4]  # Point 2   
  - [0,  -2.0, 1.2, 3] # Point 3

# 模式4   x y z yaw time
test4:
  - [-1.7,  -1.8,  1.2,  -100,   0]  # Point 1 
  - [-1.97, -9.7,  1.2,  -100,   0] # Point 2
  - [-5.5,  -9.7,  1.2,  -100,   0]  # Point 3
  - [-5.2,  -4.0,  1.2,  -100,   0]  # Point 60

test_back:
  - [-5.5,  -9.7,  1.2,  -100,   0]
  - [-1.97, -9.7,  1.2,  -100,   0] # Point 1
  - [-1.7,  -1.8,  1.2,  -100,   0]  # Point 2
  - [0,        0,  1.2,     0,   0]  # Point 3

  # - [5.8,    1.7,  1.2,  3.14,  3]  # Point 1 
  # - [6.5,   -1.4,  1.2,  1.64,  5]  # Point 2
  # - [-1.7,  -1.8,  1.2,  -1.64, 5]  # Point 3 
  # - [-1.97, -9.7,  1.2,  5.0,   5] # Point 4
  # - [-5.5,  -9.7,  1.2,  1.64,  5]  # Point 5
  # - [-5.2,  -4.0,  1.2,  1.64,  5]  # Point 6
  # - [0,      0,    1.2,  1.6,   4] # Point 7

  # 深圳点位
  # - [5.98, -3.73, 1.1 , -100, 0.05]  # Point 1    
  # - [17.06, -8.0, 1.1, -100, 0.05]  # Point 2      
  # - [17.26, -15.38, 1.1,-1.57, 0.05] # Point 3