IP:
  all: '*'                         # '*' stands for all IPs
  all_drone: 'all_drone'           # all drone, not include station
  groundStation0: 192.168.88.2   # laptop (grond station)
  drone1: 192.168.88.10           # drone 1 zld-4

  # groundStation0: 10.113.125.53
  # drone1: 10.113.125.180

  # groundStation0: 192.168.110.57   # laptop (grond station)
  # drone1: 192.168.110.216           # drone 1 zld-4

  # groundStation0: 192.168.88.5   # laptop (grond station)
  # drone1: 192.168.88.4          # drone 1 zld-4

  # groundStation0: 192.168.50.132   # laptop (grond station)
  # drone1: 192.168.50.160          # drone 1 zld-4


#  drone2: 192.168.100.107           # drone 2 zld-5
#  drone3: 192.168.100.111           # drone 3 zld-6

