IP:
  all: '*'                         # '*' stands for all IPs
  all_drone: 'all_drone'           # all drone, not include station

  groundStation0: 10.1.1.73    # laptop (ground station)
  drone1: 10.1.1.166           # drone 1
