config:
  debug: false                    # for debug only
  odom_convert: true              # convert odom to posestamped using odom_convert_node
  monitor_node: true              # check recv rate
  warn_threshold: 3               # if recv rate smaller than max_freq-warn_threashold, then warn
  monitor_rate_hz: 500            # it must be greater than max_freq

services:
  # --------- Services ---------- #
  - srv_name: /add_two_ints
    srv_type: swarm_ros_bridge/AddTwoInts
    serverIp: drone0
    clientIp:
      - drone1
      - drone2
    srcPort: 2000
    prefix: true

topics:

  # - topic_name: /drone_0_ego_planner_node/hgrid_info
  #   msg_type: visualization_msgs/MarkerArray
  #   srcIP:
  #     - drone1
  #   srcPort: 2990
  #   max_freq: 1
  #   dstIP:
  #     - groundStation0
  #   prefix: false
  #   same_prefix: false

  - topic_name: /bridge/Instruct
    msg_type: quadrotor_msgs/Instruction
    srcIP:
      - groundStation0
    srcPort: 2998
    max_freq: -1
    dstIP:
      - drone1
    prefix: false
    same_prefix: false

  - topic_name: /drone_0_ego_planner_node/planning/fsm_path
    msg_type: visualization_msgs/MarkerArray
    srcIP:
      - drone1
    srcPort: 2999
    max_freq: -1
    dstIP:
     - groundStation0
    prefix: false
    same_prefix: false

  # -- trigger from station -- #
  - topic_name: /goal_with_id_from_station
    msg_type: quadrotor_msgs/GoalSet
    srcIP:
      - groundStation0
    srcPort: 3000
    max_freq: -1
    dstIP:
      - drone1
    prefix: false
    same_prefix: false

  - topic_name: /move_base_simple/goal
    msg_type: geometry_msgs/PoseStamped
    srcIP:
      - groundStation0
    srcPort: 3001
    max_freq: -1
    dstIP:
      - drone1
    prefix: false
    same_prefix: false

  # -- navigation info -- #
  - topic_name: /drone_0_ego_planner_node/grid_map/occupancy
    msg_type: sensor_msgs/PointCloud2
    cloudCompress: true
    cloudDownsample: -1.0
    cloudType: normal
    srcIP:
      - drone1
    srcPort: 3002
    max_freq: 3
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  - topic_name: /ekf_quat/ekf_odom
    msg_type: nav_msgs/Odometry
    srcIP:
      - drone1
    srcPort: 3003
    max_freq: 24
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  - topic_name: /drone_0_ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP:
      - drone1
    srcPort: 3004
    max_freq: 5
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  - topic_name: /drone_0_ego_planner_node/init_list
    msg_type: visualization_msgs/Marker
    srcIP:
      - drone1
    srcPort: 3005
    max_freq: 5
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  - topic_name: /drone_0_ego_planner_node/far_goal_local
    msg_type: visualization_msgs/Marker
    srcIP:
      - drone1
    srcPort: 3006
    max_freq: -1
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  # -- frontiers -- #
  - topic_name: /drone_0_ego_planner_node/frontier_info
    msg_type: visualization_msgs/MarkerArray
    srcIP:
      - drone1
    srcPort: 3007
    max_freq: 3
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  # -- obj process -- #
  - topic_name: /yoloe/plot/final_vis
    msg_type: sensor_msgs/Image
    imgResizeRate: 0.8
    srcIP:
      - drone1
    srcPort: 3008
    max_freq: 10
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  - topic_name: /object_pointcloud
    msg_type: sensor_msgs/PointCloud2
    cloudCompress: true
    cloudDownsample: -1.0
    cloudType: rgb
    srcIP:
      - drone1
    srcPort: 3009
    max_freq: 2
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  - topic_name: /object_all_vis
    msg_type: visualization_msgs/MarkerArray
    srcIP:
      - drone1
    srcPort: 3010
    max_freq: 2
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  # -- scene graph -- #
  - topic_name: /scene_graph/vis
    msg_type: visualization_msgs/MarkerArray
    srcIP:
      - drone1
    srcPort: 3011
    max_freq: -1
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  - topic_name: /drone_0_ego_planner_node/skeleton_vis
    msg_type: visualization_msgs/MarkerArray
    srcIP:
      - drone1
    srcPort: 3012
    max_freq: -1
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  - topic_name: /skeleton/cluster_vis
    msg_type: visualization_msgs/MarkerArray
    srcIP:
      - drone1
    srcPort: 3013
    max_freq: -1
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  # -- LLM msgs -- #
  - topic_name: /scene_graph/prompt
    msg_type: scene_graph/PromptMsg
    srcIP:
      - drone1
    srcPort: 4010
    max_freq: -1
    dstIP:
      - groundStation0
    prefix: false
    same_prefix: false

  - topic_name: /scene_graph/llm_ans
    msg_type: scene_graph/PromptMsg
    srcIP:
      - groundStation0
    srcPort: 4011
    max_freq: -1
    dstIP:
      - drone1
    prefix: false
    same_prefix: false
