rosbag record --tcpnodelay  /mavros/imu/data /mavros/setpoint_raw/target_attitude /mavros/rc/out /Odometry /livox/imu /ekf/ekf_odom /ekf/ekf_odom_lidar /debugL_ctrl /mavros/setpoint_raw/attitude /setpoints_cmd /OdometryPropogated \
/hummingbird/command/motor_speed /hummingbird/command/mpc_trajectory /hummingbird/ground_truth/odometry /hummingbird/motor_speed /hummingbird/mpc/trajectory_predicted /hummingbird/odometry_sensor1/odometry /position_cmd /hummingbird/mpc/predicted_state /hummingbird/mpc/reference_state  /hummingbird/control_command \
/ekf/ekf_odom \
/mavros/setpoint_raw/attitude \
/mavros/esc_telemetry \
/mavros/imu/data \
/mavros/rc/in \
/controller_node/reference_path \
/controller_node/predict_path \
/controller_node/follow_path \
/controller_node/filters_data \
/controller_node/debug_data \
/vrpn_client_node/NMPC0/pose \
/controller_node/force_compensation \
/ekf/acc_filtered \
/mavros/rc/out \
/vins_estimator/path \
/vins_estimator/imu_propagate \
/position_cmd \
/odom_visualization/robot \
/sdf_map/occupancy_inflate \
/sdf_map/occupancy \
/sdf_map/esdf \
/sdf_map/depth_cloud \
/planning_vis/trajectory \
/planning/position_cmd_vis \
/setpoints_cmd \
/mavros/setpoint_raw/attitude \
/mavros/imu/data \
/ekf/ekf_odom \
/cam_t265/odom/sample \
/vins_estimator/odometry \
/mavros/imu/data_raw \
/odom_visualization/path \
/odom_visualization/pose \
/visualization/applied_trajectory \
/des_yaw_pub \
/traj_opt/debug_path \
/ekf_t265/ekf_odom_t265 \
/trajectory_generator_node/trajectory \
/traj_server/desired_acceleration \
/traj_server/desired_position \
/traj_server/desired_velocity \
/traj_server/mpc_trajectory_vis \
/traj_server/trajectory_vis \
/drone_0_ego_planner_node/grid_map/occupancy_inflate \
/drone_0_ego_planner_node/goal_point \
/drone_0_ego_planner_node/global_list \
/drone_0_ego_planner_node/optimal_list \
/drone_0_ego_planner_node/failed_list \
/drone_0_ego_planner_node/init_list